server:
  port: 9999
  
zuul:
  ignored-services: "*"
  routes:
    OAuth2Service:
      path: /auth/**
      service-id: AuthServer
      url: http://70.121.244.13:8070
      strip-prefix: false
    BookingService:
      path: /booking/**
      serviceId: Cargobooking
      stripPrefix: true
    CargoTrackerService:
      path: /tracker/**
      serviceId: Cargotracker
      stripPrefix: true
    PathfinderService: 
      path: /pathfinder/**
      serviceId: Pathfinder
      stripPrefix: true
    CargoUserService: 
      path: /user/**
      serviceId: Cargouser
      stripPrefix: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false 
